package sql

import (
	"fmt"
	"reflect"
	"testing"
)

func TestColumnParse(t *testing.T) {
	columns := []string{
		"code        char(5) CONSTRAINT firstkey PRIMARY KEY",
		"title       varchar(40) NOT NULL",
		"did         integer NOT NULL",
		"date_prod   date",
		"kind        varchar(10)",
		"len         interval hour to minute",
		"did    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY",
		"name   varchar(40) NOT NULL CHECK (name <> '')",
	}

	resp, err := parseColumns(columns)

	for _, column := range resp {
		cType := reflect.TypeOf(column)
		cValue := reflect.ValueOf(column)

		fmt.Println("-------" + column.Name + "-------")
		for i := 0; i < cType.NumField(); i++ {
			fmt.Printf("%s: %v\n", cType.Field(i).Name, cValue.Field(i).Interface())
		}

	}

	if err != nil {
		t.Errorf("Error parsing columns: %v", err)
	}
}
